version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: 'gitlab'
    #environment:
    #  GITLAB_OMNIBUS_CONFIG: |
    #    external_url 'http://localh:8929'
    ports:
      - "8929:8929"
      - "2222:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - nebula_net

networks:
  nebula_net:
    external: true

volumes:
   gitlab_config:
    external: true
  gitlab_logs:
    external: true
  gitlab_data:
    external: true